services:
  type: web
  name: alog_backend-1
  env: node
  buildCommand: npm install && npx prisma migrate dev --name init && npx prisma db push && npx prisma generate && npx prisma db push && npm run build
  startCommand: npm start
