services:
  type: web
  name: alog_backend-1
  env: node
  buildCommand: npm install  && cd src/prisma && npx prisma migrate dev --name init && npx prisma db push && npx prisma generate && npx prisma db push && cd ../.. && npm run build
  startCommand: npm start
